"""Generate book/chapters/credits.tex (Image Credits) from book/figs/photos/<name>.json sidecars.

Only photos actually used in the book (\\mdcphoto{name}...) are listed, ordered by first use.
    python book/tools/gen_credits.py
"""
import glob, json, os, re

HERE = os.path.dirname(os.path.abspath(__file__))
BOOK = os.path.abspath(os.path.join(HERE, ".."))
creds = {os.path.basename(f)[:-5]: json.load(open(f, encoding="utf-8"))
         for f in glob.glob(os.path.join(BOOK, "figs", "photos", "*.json"))}


def tex(s):
    s = s.replace("\\", "/")
    for a, b in [("&", r"\&"), ("%", r"\%"), ("$", r"\$"), ("#", r"\#"), ("_", r"\_"),
                 ("{", r"\{"), ("}", r"\}"), ("~", r"\textasciitilde{}"), ("^", r"\textasciicircum{}")]:
        s = s.replace(a, b)
    return s


order, where = [], {}
files = sorted(glob.glob(os.path.join(BOOK, "chapters", "ch*.tex"))) + \
    sorted(glob.glob(os.path.join(BOOK, "chapters", "app*.tex")))
for f in files:
    ch = os.path.basename(f)[:-4]
    for m in re.finditer(r"\\mdcphoto(?:\[[^\]]*\])?\{([^}]+)\}", open(f, encoding="utf-8").read()):
        n = m.group(1)
        if n not in where:
            order.append(n)
            where[n] = ch
lines = [r"\chapter*{Image Credits}", r"\addcontentsline{toc}{chapter}{Image Credits}",
         r"\markboth{Image Credits}{Image Credits}", "",
         "Photographs in this book are reproduced from Wikimedia Commons under the licenses shown. "
         "Public-domain works are credited to their creators where known. All diagrams and data "
         "figures were created for this book and are generated by the Python scripts in the "
         "companion repository.", "",
         r"\begin{small}\begin{itemize}[leftmargin=0pt,itemsep=2pt,label={}]"]
missing = []
for n in order:
    c = creds.get(n)
    if not c:
        missing.append(n)
        continue
    chap = where[n].replace("ch", "Ch.~").replace("app", "App.~")
    if chap.startswith("Ch.~0"):
        chap = "Ch.~" + chap[4:]
    title = tex(c["title"].replace("File:", ""))
    lines.append(rf"\item \textbf{{{chap}}}, Figure~\ref{{fig:{n}}}: {tex(c['author'][:120])}. "
                 rf"\emph{{{title}}}. {tex(c['license'])}. \url{{{c['source']}}}")
lines += [r"\end{itemize}\end{small}", ""]
open(os.path.join(BOOK, "chapters", "credits.tex"), "w", encoding="utf-8").write("\n".join(lines))
# Short per-photo credit macros used by \mdcphoto captions.
macros = ["% generated by book/tools/gen_credits.py -- do not edit"]
for n, c in sorted(creds.items()):
    who = c["author"] if c["author"] and c["author"] != "Unknown" else ""
    who = re.sub(r"\s*\(.*?\)\s*", " ", who).strip()[:60]
    short = (who + ", " if who else "") + c["license"]
    macros.append(r"\expandafter\def\csname mdccred@" + n + r"\endcsname{" + tex(short) + "}")
open(os.path.join(BOOK, "figs", "photos", "credits_macros.tex"), "w", encoding="utf-8").write("\n".join(macros) + "\n")
print(f"{len(order) - len(missing)} credits written" + (f"; MISSING credits for {missing}" if missing else ""))
