"""Generate book/chapters/credits.tex (Image Credits) from book/figs/photos/<name>.json sidecars.

Only photos actually used in the book (\\mdcphoto{name}...) are listed, ordered by first use.
    python book/tools/gen_credits.py
"""
import glob, json, os, re

HERE = os.path.dirname(os.path.abspath(__file__))
BOOK = os.path.abspath(os.path.join(HERE, ".."))
creds = {os.path.basename(f)[:-5]: json.load(open(f, encoding="utf-8"))
         for f in glob.glob(os.path.join(BOOK, "figs", "photos", "*.json"))}


_CYR = dict(zip("абвгдеёжзийклмнопрстуфхцчшщъыьэюяАБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ",
                "a b v g d e e zh z i i k l m n o p r s t u f kh ts ch sh shch '' y ' e yu ya "
                "A B V G D E E Zh Z I I K L M N O P R S T U F Kh Ts Ch Sh Shch '' Y ' E Yu Ya".split()))


def _printable(s):
    """Transliterate Cyrillic; drop other characters the book's T1/utf8 setup cannot print."""
    import unicodedata
    out = []
    for ch in s:
        if ch in _CYR:
            out.append(_CYR[ch])
        elif ord(ch) < 0x250 or ch in "–—‘’“”…·×°µ":
            out.append(ch)
        else:
            out.append(unicodedata.normalize("NFKD", ch).encode("ascii", "ignore").decode())
    return "".join(out)


def tex(s):
    s = _printable(s).replace("\\", "/")
    for a, b in [("&", r"\&"), ("%", r"\%"), ("$", r"\$"), ("#", r"\#"), ("_", r"\_"),
                 ("{", r"\{"), ("}", r"\}"), ("~", r"\textasciitilde{}"), ("^", r"\textasciicircum{}")]:
        s = s.replace(a, b)
    return s


order, where = [], {}
files = sorted(glob.glob(os.path.join(BOOK, "chapters", "ch*.tex"))) + \
    sorted(glob.glob(os.path.join(BOOK, "chapters", "app*.tex")))
# A photo counts as used wherever its name appears as a whole token in a chapter -- \mdcphoto,
# \mdcsidephoto, \mdcpairany, chapter-local macros or a raw \includegraphics{figs/photos/name}.
# Order by first appearance in the book.
names = sorted(creds, key=len, reverse=True)
for f in files:
    ch = os.path.basename(f)[:-4]
    text = re.sub(r"(?m)%.*$", "", open(f, encoding="utf-8").read())   # ignore commented-out uses
    hits = []
    for n in names:
        m = re.search(r"(?<![A-Za-z0-9_])" + re.escape(n) + r"(?![A-Za-z0-9_])", text)
        if m and n not in where:
            hits.append((m.start(), n))
    for _, n in sorted(hits):
        order.append(n)
        where[n] = ch
# Only link "Figure~\ref{fig:name}" when that label exists (most photo macros create it).
aux = ""
for a in [os.path.join(BOOK, "main.aux")] + glob.glob(os.path.join(BOOK, "chapters", "*.aux")):
    if os.path.exists(a):
        aux += open(a, encoding="latin-1").read()
lines = [r"\chapter*{Image Credits}", r"\addcontentsline{toc}{chapter}{Image Credits}",
         r"\markboth{Image Credits}{Image Credits}", "",
         "Photographs in this book are reproduced from Wikimedia Commons under the licenses shown. "
         "Public-domain works are credited to their creators where known. All diagrams and data "
         "figures were created for this book and are generated by the Python scripts in the "
         "companion repository.", "",
         # long Commons file names/URLs: ragged right, and let \url break after any character
         r"\begingroup\raggedright\sloppy",
         r"\expandafter\def\expandafter\UrlBreaks\expandafter{\UrlBreaks"
         + "".join(r"\do " + ch for ch in "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789")
         + "}",
         r"\begin{small}\begin{itemize}[leftmargin=0pt,itemsep=2pt,label={}]"]
missing = []
for n in order:
    c = creds.get(n)
    if not c:
        missing.append(n)
        continue
    chap = where[n].replace("ch", "Ch.~").replace("app", "App.~")
    if chap.startswith("Ch.~0"):
        chap = "Ch.~" + chap[5:]
    title = tex(c["title"].replace("File:", ""))
    title = title.replace("\\_", "\\_\\allowbreak{}").replace("-", "-\\allowbreak{}").replace(".", ".\\allowbreak{}")
    ref = rf", Figure~\ref{{fig:{n}}}" if ("{fig:" + n + "}") in aux else ""
    lines.append(rf"\item \textbf{{{chap}}}{ref}: {tex(c['author'][:120])}. "
                 rf"\emph{{{title}}}. {tex(c['license'])}. \url{{{c['source']}}}")
lines += [r"\end{itemize}\end{small}", r"\endgroup", ""]
open(os.path.join(BOOK, "chapters", "credits.tex"), "w", encoding="utf-8").write("\n".join(lines))
# Short per-photo credit macros used by \mdcphoto captions.
macros = ["% generated by book/tools/gen_credits.py -- do not edit"]
for n, c in sorted(creds.items()):
    who = c["author"] if c["author"] and c["author"] != "Unknown" else ""
    who = re.sub(r"\s*\(.*?\)\s*", " ", who).strip()[:60]
    short = (who + ", " if who else "") + c["license"]
    macros.append(r"\expandafter\def\csname mdccred@" + n + r"\endcsname{" + tex(short) + "}")
open(os.path.join(BOOK, "figs", "photos", "credits_macros.tex"), "w", encoding="utf-8").write("\n".join(macros) + "\n")
print(f"{len(order) - len(missing)} credits written" + (f"; MISSING credits for {missing}" if missing else ""))
