"""Generate book/chapters/references.tex from bibdata.py; check coverage vs snapshot.json."""
import json, os, re, sys
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from bibdata import DATA

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "chapters", "references.tex")
LABELS = {1: "history", 2: "signals", 3: "noise", 4: "analog", 5: "pcm", 6: "dsp", 7: "sdr",
          8: "baseband", 9: "modulation", 10: "sync", 11: "channels", 12: "equalization",
          13: "infotheory", 14: "classiccodes", 15: "moderncodes", 16: "sourcecoding",
          17: "ofdm", 18: "spreadspectrum", 19: "mimo", 20: "multipleaccess", 21: "cellular",
          22: "wifi", 23: "satellite", 24: "wireline", 25: "sixg"}
SECTIONS = [("B", "Books"), ("P", "Classic and research papers"),
            ("S", "Standards, specifications and regulations"),
            ("O", "Other: application notes, manuals, software and websites")]

def natkey(s):
    return [int(t) if t.isdigit() else t for t in re.split(r"(\d+)", s.lower())]

def parse():
    ents = []
    for ln in DATA.strip().splitlines():
        ln = ln.strip()
        if not ln or ln.startswith("#"):
            continue
        sec, key, chs, text = ln.split("|", 3)
        ents.append(dict(sec=sec, key=key, chs=chs.split(), text=text.strip().rstrip(".")))
    keys = [e["key"] for e in ents]
    dup = {k for k in keys if keys.count(k) > 1}
    if dup:
        sys.exit(f"duplicate keys: {dup}")
    return ents

def chapters_str(chs):
    nums = sorted(int(c) for c in chs if c.isdigit())
    apps = sorted(c for c in chs if not c.isdigit())
    parts = []
    if nums:
        parts.append(("Ch.~" if len(nums) == 1 else "Chs.~") +
                     ", ".join(f"\\hyperref[ch:{LABELS[n]}]{{{n}}}" for n in nums))
    if apps:
        parts.append("App.~" + ", ".join(f"\\hyperref[app{a}]{{{a}}}" for a in apps))
    return "; ".join(parts)

HEADER = r"""% =====================================================================
% References -- consolidated from every chapter's Further Reading section.
% GENERATED by a script from a curated list; edit the list, not by hand.
% =====================================================================
\chapter*{References}
\addcontentsline{toc}{chapter}{References}
\markboth{References}{References}
\label{references}

\providecommand{\citedin}[1]{{\unskip\nobreak\hskip1.5em plus 1fil\penalty50
  \hskip0pt plus -1fil\hbox{}\nobreak\hskip0pt plus 1fil
  \mbox{\footnotesize\itshape #1}\parfillskip=0pt\finalhyphendemerits=0\par}}

Every chapter of this book ends with a \emph{Further Reading} section in which each work is
annotated: what it covers, why it is worth your time, and which part of the chapter it
supports. This list collects every work cited in those sections into one alphabetized
reference, so that you can find a book or paper again without remembering which chapter
recommended it. At the right of each entry are the chapters (and appendices) that cite it;
the numbers are links, and the annotations are to be found in those chapters. Books, papers,
standards and other sources are listed separately; standards are ordered by organization and
then by document number. Standards bodies revise their documents continually, so unless an
edition is stated, consult the current version.
"""

def main():
    ents = parse()
    out = [HEADER]
    counts = {}
    for sec, title in SECTIONS:
        es = sorted((e for e in ents if e["sec"] == sec), key=lambda e: natkey(e["key"]))
        counts[title] = len(es)
        out.append(f"\n\\section*{{{title}}}\n\\addcontentsline{{toc}}{{section}}{{{title}}}\n\\markright{{{title.split(':')[0]}}}\n")
        out.append("\\begingroup\\small\n\\begin{itemize}[leftmargin=1.5em,itemindent=-1.5em,"
                   "itemsep=1.5pt plus 1pt,parsep=0pt,topsep=4pt,label={}]\\rightskip=0pt plus 3em\\relax\n")
        for e in es:
            out.append(f"\\item {e['text']}.\\citedin{{{chapters_str(e['chs'])}}}\n")
        out.append("\\end{itemize}\n\\endgroup\n")
    open(OUT, "w", encoding="utf-8").write("".join(out))
    print("wrote", OUT)
    for t, n in counts.items():
        print(f"  {n:4d}  {t}")
    print(f"  {len(ents):4d}  total")
    # coverage: each chapter's cited set vs snapshot item count
    snap = json.load(open(os.path.join(HERE, "snapshot.json"), encoding="utf-8"))
    per = {}
    for e in ents:
        for c in e["chs"]:
            per.setdefault(c, []).append(e)
    print("\nper-chapter: snapshot items -> bibliography entries")
    for name, items in snap.items():
        c = str(int(name[2:])) if name.startswith("ch") else name[3:]
        print(f"  {name}: {len(items):3d} items -> {len(per.get(c, [])):3d} entries")
    # surname check: first capitalised surname-ish token of each item must appear in some entry
    print("\nsurname check (possible omissions):")
    for name, items in snap.items():
        c = str(int(name[2:])) if name.startswith("ch") else name[3:]
        blob = " ".join(e["text"] for e in per.get(c, []))
        for it in items:
            for m in re.finditer(r"(?:[A-Z]\.~)+(?:[A-Z]\.~)*([^\s,]+)", it):
                sn = m.group(1).rstrip(".,;")
                if sn not in blob:
                    print(f"  {name}: '{sn}' not found  <- {it[:90]}")

if __name__ == "__main__":
    main()
